[workspace]
members = [
    "app/page-log",
    "app/page-relay",
    "app/browser-page-renderer",
    "app/core",
    "app/document",
    "app/tablet",
    "app/telegram-bot",
    "reverse-engineering/native-observer",
    "reverse-engineering/native-replay",
]
resolver = "3"

[profile.release]
lto = true
opt-level = "s"
panic = "abort"
strip = true
